//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercuryMapper.Assets.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MercuryMapper.Assets.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        public static string BonusType_Bonus {
            get {
                return ResourceManager.GetString("BonusType_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string BonusType_None {
            get {
                return ResourceManager.GetString("BonusType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Note.
        /// </summary>
        public static string BonusType_RNote {
            get {
                return ResourceManager.GetString("BonusType_RNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string ChartProperties_Artist {
            get {
                return ResourceManager.GetString("ChartProperties_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Author.
        /// </summary>
        public static string ChartProperties_Author {
            get {
                return ResourceManager.GetString("ChartProperties_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM.
        /// </summary>
        public static string ChartProperties_Bpm {
            get {
                return ResourceManager.GetString("ChartProperties_Bpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Threshold.
        /// </summary>
        public static string ChartProperties_ClearThreshold {
            get {
                return ResourceManager.GetString("ChartProperties_ClearThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string ChartProperties_Level {
            get {
                return ResourceManager.GetString("ChartProperties_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Offset.
        /// </summary>
        public static string ChartProperties_MovieOffset {
            get {
                return ResourceManager.GetString("ChartProperties_MovieOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Filepath.
        /// </summary>
        public static string ChartProperties_MusicFilePath {
            get {
                return ResourceManager.GetString("ChartProperties_MusicFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string ChartProperties_Offset {
            get {
                return ResourceManager.GetString("ChartProperties_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Preview.
        /// </summary>
        public static string ChartProperties_PlayPreview {
            get {
                return ResourceManager.GetString("ChartProperties_PlayPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Length.
        /// </summary>
        public static string ChartProperties_PreviewLength {
            get {
                return ResourceManager.GetString("ChartProperties_PreviewLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Start.
        /// </summary>
        public static string ChartProperties_PreviewTime {
            get {
                return ResourceManager.GetString("ChartProperties_PreviewTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Signature.
        /// </summary>
        public static string ChartProperties_TimeSignature {
            get {
                return ResourceManager.GetString("ChartProperties_TimeSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ChartProperties_Title {
            get {
                return ResourceManager.GetString("ChartProperties_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Gimmick.
        /// </summary>
        public static string Editor_AddGimmick {
            get {
                return ResourceManager.GetString("Editor_AddGimmick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bake Hold.
        /// </summary>
        public static string Editor_BakeHoldNote {
            get {
                return ResourceManager.GetString("Editor_BakeHoldNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat.
        /// </summary>
        public static string Editor_Beat {
            get {
                return ResourceManager.GetString("Editor_Beat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Select.
        /// </summary>
        public static string Editor_BoxSelect {
            get {
                return ResourceManager.GetString("Editor_BoxSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Audio.
        /// </summary>
        public static string Editor_ChartInfo_ChartAudio {
            get {
                return ResourceManager.GetString("Editor_ChartInfo_ChartAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Playback Speed.
        /// </summary>
        public static string Editor_DecreasePlaybackSpeed {
            get {
                return ResourceManager.GetString("Editor_DecreasePlaybackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Editor_Delete {
            get {
                return ResourceManager.GetString("Editor_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Gimmick.
        /// </summary>
        public static string Editor_DeleteGimmick {
            get {
                return ResourceManager.GetString("Editor_DeleteGimmick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selection.
        /// </summary>
        public static string Editor_DeleteSelection {
            get {
                return ResourceManager.GetString("Editor_DeleteSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect All.
        /// </summary>
        public static string Editor_DeselectAll {
            get {
                return ResourceManager.GetString("Editor_DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Gimmick.
        /// </summary>
        public static string Editor_EditGimmick {
            get {
                return ResourceManager.GetString("Editor_EditGimmick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Hold.
        /// </summary>
        public static string Editor_EditHold {
            get {
                return ResourceManager.GetString("Editor_EditHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit [Type].
        /// </summary>
        public static string Editor_EditNoteProperties {
            get {
                return ResourceManager.GetString("Editor_EditNoteProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit [Shape].
        /// </summary>
        public static string Editor_EditNoteShape {
            get {
                return ResourceManager.GetString("Editor_EditNoteShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit [Both].
        /// </summary>
        public static string Editor_EditNoteShapeProperties {
            get {
                return ResourceManager.GetString("Editor_EditNoteShapeProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Hold.
        /// </summary>
        public static string Editor_EndHold {
            get {
                return ResourceManager.GetString("Editor_EndHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Info.
        /// </summary>
        public static string Editor_ExpanderHeader_ChartInfo {
            get {
                return ResourceManager.GetString("Editor_ExpanderHeader_ChartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Gimmicks.
        /// </summary>
        public static string Editor_ExpanderHeader_ModifyGimmicks {
            get {
                return ResourceManager.GetString("Editor_ExpanderHeader_ModifyGimmicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Notes.
        /// </summary>
        public static string Editor_ExpanderHeader_ModifyNotes {
            get {
                return ResourceManager.GetString("Editor_ExpanderHeader_ModifyNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Settings.
        /// </summary>
        public static string Editor_ExpanderHeader_QuickSettings {
            get {
                return ResourceManager.GetString("Editor_ExpanderHeader_QuickSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Info.
        /// </summary>
        public static string Editor_ExpanderHeader_SelectionInfo {
            get {
                return ResourceManager.GetString("Editor_ExpanderHeader_SelectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gimmick Type.
        /// </summary>
        public static string Editor_GimmickType {
            get {
                return ResourceManager.GetString("Editor_GimmickType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest.
        /// </summary>
        public static string Editor_HighlightNearest {
            get {
                return ResourceManager.GetString("Editor_HighlightNearest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Nearest Note.
        /// </summary>
        public static string Editor_HighlightNearestNote {
            get {
                return ResourceManager.GetString("Editor_HighlightNearestNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        public static string Editor_HighlightNext {
            get {
                return ResourceManager.GetString("Editor_HighlightNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Next Note.
        /// </summary>
        public static string Editor_HighlightNextNote {
            get {
                return ResourceManager.GetString("Editor_HighlightNextNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Previous.
        /// </summary>
        public static string Editor_HighlightPrev {
            get {
                return ResourceManager.GetString("Editor_HighlightPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Prev Note.
        /// </summary>
        public static string Editor_HighlightPrevNote {
            get {
                return ResourceManager.GetString("Editor_HighlightPrevNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear.
        /// </summary>
        public static string Editor_HoldEase_Linear {
            get {
                return ResourceManager.GetString("Editor_HoldEase_Linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear+ In.
        /// </summary>
        public static string Editor_HoldEase_LinearPlusIn {
            get {
                return ResourceManager.GetString("Editor_HoldEase_LinearPlusIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear+ Out.
        /// </summary>
        public static string Editor_HoldEase_LinearPlusOut {
            get {
                return ResourceManager.GetString("Editor_HoldEase_LinearPlusOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quad In.
        /// </summary>
        public static string Editor_HoldEase_QuadIn {
            get {
                return ResourceManager.GetString("Editor_HoldEase_QuadIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quad Out.
        /// </summary>
        public static string Editor_HoldEase_QuadOut {
            get {
                return ResourceManager.GetString("Editor_HoldEase_QuadOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharp In.
        /// </summary>
        public static string Editor_HoldEase_SharpIn {
            get {
                return ResourceManager.GetString("Editor_HoldEase_SharpIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharp Out.
        /// </summary>
        public static string Editor_HoldEase_SharpOut {
            get {
                return ResourceManager.GetString("Editor_HoldEase_SharpOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sine In.
        /// </summary>
        public static string Editor_HoldEase_SineIn {
            get {
                return ResourceManager.GetString("Editor_HoldEase_SineIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sine Out.
        /// </summary>
        public static string Editor_HoldEase_SineOut {
            get {
                return ResourceManager.GetString("Editor_HoldEase_SineOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth In.
        /// </summary>
        public static string Editor_HoldEase_SmoothIn {
            get {
                return ResourceManager.GetString("Editor_HoldEase_SmoothIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth Out.
        /// </summary>
        public static string Editor_HoldEase_SmoothOut {
            get {
                return ResourceManager.GetString("Editor_HoldEase_SmoothOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Ease.
        /// </summary>
        public static string Editor_HoldEaseHeader {
            get {
                return ResourceManager.GetString("Editor_HoldEaseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Playback Speed.
        /// </summary>
        public static string Editor_IncreasePlaybackSpeed {
            get {
                return ResourceManager.GetString("Editor_IncreasePlaybackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Editor_Insert {
            get {
                return ResourceManager.GetString("Editor_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Segment.
        /// </summary>
        public static string Editor_InsertHoldSegment {
            get {
                return ResourceManager.GetString("Editor_InsertHoldSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer: Gimmick.
        /// </summary>
        public static string Editor_LayerGimmick {
            get {
                return ResourceManager.GetString("Editor_LayerGimmick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer: Mask.
        /// </summary>
        public static string Editor_LayerMask {
            get {
                return ResourceManager.GetString("Editor_LayerMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer: Note.
        /// </summary>
        public static string Editor_LayerNote {
            get {
                return ResourceManager.GetString("Editor_LayerNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask Direction.
        /// </summary>
        public static string Editor_MaskDirection {
            get {
                return ResourceManager.GetString("Editor_MaskDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure.
        /// </summary>
        public static string Editor_Measure {
            get {
                return ResourceManager.GetString("Editor_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror Axis.
        /// </summary>
        public static string Editor_MirrorAxis {
            get {
                return ResourceManager.GetString("Editor_MirrorAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror.
        /// </summary>
        public static string Editor_MirrorNote {
            get {
                return ResourceManager.GetString("Editor_MirrorNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Chart.
        /// </summary>
        public static string Editor_NewChart {
            get {
                return ResourceManager.GetString("Editor_NewChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected audio file couldn&apos;t be found..
        /// </summary>
        public static string Editor_NewChartInvalidAudio {
            get {
                return ResourceManager.GetString("Editor_NewChartInvalidAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart has invalid BPM. BPM must be above zero..
        /// </summary>
        public static string Editor_NewChartInvalidBpm {
            get {
                return ResourceManager.GetString("Editor_NewChartInvalidBpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart has invalid Time Signature. Upper and Lower must be above zero..
        /// </summary>
        public static string Editor_NewChartInvalidTimeSig {
            get {
                return ResourceManager.GetString("Editor_NewChartInvalidTimeSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Holds selected!.
        /// </summary>
        public static string Editor_NoHoldsSelected {
            get {
                return ResourceManager.GetString("Editor_NoHoldsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select any segment of a hold note to run this algorithm on it..
        /// </summary>
        public static string Editor_NoHoldsSelectedTip {
            get {
                return ResourceManager.GetString("Editor_NoHoldsSelectedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Caps.
        /// </summary>
        public static string Editor_NoteCaps {
            get {
                return ResourceManager.GetString("Editor_NoteCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Type.
        /// </summary>
        public static string Editor_NoteType {
            get {
                return ResourceManager.GetString("Editor_NoteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Editor_Pause {
            get {
                return ResourceManager.GetString("Editor_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Editor_Play {
            get {
                return ResourceManager.GetString("Editor_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Editor_Position {
            get {
                return ResourceManager.GetString("Editor_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position - [Quick Edit].
        /// </summary>
        public static string Editor_QuickEditDecreasePosition {
            get {
                return ResourceManager.GetString("Editor_QuickEditDecreasePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size - [Quick Edit].
        /// </summary>
        public static string Editor_QuickEditDecreaseSize {
            get {
                return ResourceManager.GetString("Editor_QuickEditDecreaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp - [Quick Edit].
        /// </summary>
        public static string Editor_QuickEditDecreaseTimestamp {
            get {
                return ResourceManager.GetString("Editor_QuickEditDecreaseTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position + [Quick Edit].
        /// </summary>
        public static string Editor_QuickEditIncreasePosition {
            get {
                return ResourceManager.GetString("Editor_QuickEditIncreasePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size + [Quick Edit].
        /// </summary>
        public static string Editor_QuickEditIncreaseSize {
            get {
                return ResourceManager.GetString("Editor_QuickEditIncreaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp + [Quick Edit].
        /// </summary>
        public static string Editor_QuickEditIncreaseTimestamp {
            get {
                return ResourceManager.GetString("Editor_QuickEditIncreaseTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string Editor_SelectAll {
            get {
                return ResourceManager.GetString("Editor_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Highlighted Note.
        /// </summary>
        public static string Editor_SelectHighlightedNote {
            get {
                return ResourceManager.GetString("Editor_SelectHighlightedNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Hold Note References.
        /// </summary>
        public static string Editor_SelectHoldReferences {
            get {
                return ResourceManager.GetString("Editor_SelectHoldReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Notes.
        /// </summary>
        public static string Editor_SelectionInfo_SelectedNotes {
            get {
                return ResourceManager.GetString("Editor_SelectionInfo_SelectedNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Render False.
        /// </summary>
        public static string Editor_SetRenderFalse {
            get {
                return ResourceManager.GetString("Editor_SetRenderFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Render True.
        /// </summary>
        public static string Editor_SetRenderTrue {
            get {
                return ResourceManager.GetString("Editor_SetRenderTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Editor_Size {
            get {
                return ResourceManager.GetString("Editor_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stitch Hold.
        /// </summary>
        public static string Editor_StitchHold {
            get {
                return ResourceManager.GetString("Editor_StitchHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autosave found. Timestamp:.
        /// </summary>
        public static string Generic_AutosaveFound {
            get {
                return ResourceManager.GetString("Generic_AutosaveFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to open it?.
        /// </summary>
        public static string Generic_AutosavePrompt {
            get {
                return ResourceManager.GetString("Generic_AutosavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Generic_Close {
            get {
                return ResourceManager.GetString("Generic_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Generic_Create {
            get {
                return ResourceManager.GetString("Generic_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Chart Note is missing!.
        /// </summary>
        public static string Generic_EndOfChartWarning {
            get {
                return ResourceManager.GetString("Generic_EndOfChartWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place an End of Chart note at least a Measure after the last playable note. Without it, the game would crash..
        /// </summary>
        public static string Generic_EndOfChartWarningExplanation {
            get {
                return ResourceManager.GetString("Generic_EndOfChartWarningExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Generic_Export {
            get {
                return ResourceManager.GetString("Generic_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generic_Generate {
            get {
                return ResourceManager.GetString("Generic_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio not found..
        /// </summary>
        public static string Generic_InvalidAudioWarning {
            get {
                return ResourceManager.GetString("Generic_InvalidAudioWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Generic_No {
            get {
                return ResourceManager.GetString("Generic_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Generic_None {
            get {
                return ResourceManager.GetString("Generic_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Generic_Ok {
            get {
                return ResourceManager.GetString("Generic_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Close.
        /// </summary>
        public static string Generic_SaveAndClose {
            get {
                return ResourceManager.GetString("Generic_SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart is unsaved. Would you like to save?.
        /// </summary>
        public static string Generic_SaveWarning {
            get {
                return ResourceManager.GetString("Generic_SaveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart either has no audio or the specified audio file was not found.
        ///Would you like to manually select a file?.
        /// </summary>
        public static string Generic_SelectAudioPrompt {
            get {
                return ResourceManager.GetString("Generic_SelectAudioPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string Generic_SelectFile {
            get {
                return ResourceManager.GetString("Generic_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Generic_Yes {
            get {
                return ResourceManager.GetString("Generic_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM.
        /// </summary>
        public static string Gimmick_BpmChange {
            get {
                return ResourceManager.GetString("Gimmick_BpmChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HiSpeed.
        /// </summary>
        public static string Gimmick_HiSpeedChange {
            get {
                return ResourceManager.GetString("Gimmick_HiSpeedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        public static string Gimmick_Reverse {
            get {
                return ResourceManager.GetString("Gimmick_Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Effect End.
        /// </summary>
        public static string Gimmick_ReverseEffectEnd {
            get {
                return ResourceManager.GetString("Gimmick_ReverseEffectEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Effect Start.
        /// </summary>
        public static string Gimmick_ReverseEffectStart {
            get {
                return ResourceManager.GetString("Gimmick_ReverseEffectStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Note Zone End.
        /// </summary>
        public static string Gimmick_ReverseNoteEnd {
            get {
                return ResourceManager.GetString("Gimmick_ReverseNoteEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Gimmick_Stop {
            get {
                return ResourceManager.GetString("Gimmick_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop End.
        /// </summary>
        public static string Gimmick_StopEnd {
            get {
                return ResourceManager.GetString("Gimmick_StopEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Start.
        /// </summary>
        public static string Gimmick_StopStart {
            get {
                return ResourceManager.GetString("Gimmick_StopStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Signature.
        /// </summary>
        public static string Gimmick_TimeSigChange {
            get {
                return ResourceManager.GetString("Gimmick_TimeSigChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Center.
        /// </summary>
        public static string MaskDirection_Center {
            get {
                return ResourceManager.GetString("MaskDirection_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clockwise.
        /// </summary>
        public static string MaskDirection_Clockwise {
            get {
                return ResourceManager.GetString("MaskDirection_Clockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counterclockwise.
        /// </summary>
        public static string MaskDirection_Counterclockwise {
            get {
                return ResourceManager.GetString("MaskDirection_Counterclockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Menu_Copy {
            get {
                return ResourceManager.GetString("Menu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Menu_Cut {
            get {
                return ResourceManager.GetString("Menu_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Menu_Export {
            get {
                return ResourceManager.GetString("Menu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export for Mercury.
        /// </summary>
        public static string Menu_ExportMercury {
            get {
                return ResourceManager.GetString("Menu_ExportMercury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export for Saturn.
        /// </summary>
        public static string Menu_ExportSaturn {
            get {
                return ResourceManager.GetString("Menu_ExportSaturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Saturn Folder.
        /// </summary>
        public static string Menu_ExportSaturnFolder {
            get {
                return ResourceManager.GetString("Menu_ExportSaturnFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix off-by-one Errors.
        /// </summary>
        public static string Menu_FixOffByOneErrors {
            get {
                return ResourceManager.GetString("Menu_FixOffByOneErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Jagged Holds.
        /// </summary>
        public static string Menu_JaggedHolds {
            get {
                return ResourceManager.GetString("Menu_JaggedHolds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror Chart.
        /// </summary>
        public static string Menu_MirrorChart {
            get {
                return ResourceManager.GetString("Menu_MirrorChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Menu_New {
            get {
                return ResourceManager.GetString("Menu_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Menu_Open {
            get {
                return ResourceManager.GetString("Menu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Menu_Paste {
            get {
                return ResourceManager.GetString("Menu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconstruct Holds.
        /// </summary>
        public static string Menu_ReconstructHolds {
            get {
                return ResourceManager.GetString("Menu_ReconstructHolds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Menu_Redo {
            get {
                return ResourceManager.GetString("Menu_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string Menu_SaveAs {
            get {
                return ResourceManager.GetString("Menu_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Chart.
        /// </summary>
        public static string Menu_ShiftChart {
            get {
                return ResourceManager.GetString("Menu_ShiftChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Menu_Undo {
            get {
                return ResourceManager.GetString("Menu_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MenuHeader_Edit {
            get {
                return ResourceManager.GetString("MenuHeader_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuHeader_File {
            get {
                return ResourceManager.GetString("MenuHeader_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string MenuHeader_Select {
            get {
                return ResourceManager.GetString("MenuHeader_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string MenuHeader_Tools {
            get {
                return ResourceManager.GetString("MenuHeader_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain.
        /// </summary>
        public static string Note_Chain {
            get {
                return ResourceManager.GetString("Note_Chain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Chart.
        /// </summary>
        public static string Note_EndOfChart {
            get {
                return ResourceManager.GetString("Note_EndOfChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string Note_Highlight {
            get {
                return ResourceManager.GetString("Note_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        public static string Note_Hold {
            get {
                return ResourceManager.GetString("Note_Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold End.
        /// </summary>
        public static string Note_HoldEnd {
            get {
                return ResourceManager.GetString("Note_HoldEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Segment.
        /// </summary>
        public static string Note_HoldSegment {
            get {
                return ResourceManager.GetString("Note_HoldSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Segment [No Render].
        /// </summary>
        public static string Note_HoldSegmentNoRender {
            get {
                return ResourceManager.GetString("Note_HoldSegmentNoRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Start.
        /// </summary>
        public static string Note_HoldStart {
            get {
                return ResourceManager.GetString("Note_HoldStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Surface Far.
        /// </summary>
        public static string Note_HoldSurfaceFar {
            get {
                return ResourceManager.GetString("Note_HoldSurfaceFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Surface Near.
        /// </summary>
        public static string Note_HoldSurfaceNear {
            get {
                return ResourceManager.GetString("Note_HoldSurfaceNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask Add.
        /// </summary>
        public static string Note_MaskAdd {
            get {
                return ResourceManager.GetString("Note_MaskAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask Remove.
        /// </summary>
        public static string Note_MaskRemove {
            get {
                return ResourceManager.GetString("Note_MaskRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string Note_Selection {
            get {
                return ResourceManager.GetString("Note_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↩ Slide CW.
        /// </summary>
        public static string Note_SlideClockwise {
            get {
                return ResourceManager.GetString("Note_SlideClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↪ Slide CCW.
        /// </summary>
        public static string Note_SlideCounterclockwise {
            get {
                return ResourceManager.GetString("Note_SlideCounterclockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↓ Snap BW.
        /// </summary>
        public static string Note_SnapBackward {
            get {
                return ResourceManager.GetString("Note_SnapBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↑ Snap FW.
        /// </summary>
        public static string Note_SnapForward {
            get {
                return ResourceManager.GetString("Note_SnapForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch.
        /// </summary>
        public static string Note_Touch {
            get {
                return ResourceManager.GetString("Note_Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string SaturnExport_Artist {
            get {
                return ResourceManager.GetString("SaturnExport_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM.
        /// </summary>
        public static string SaturnExport_Bpm {
            get {
                return ResourceManager.GetString("SaturnExport_Bpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beyond Diff.
        /// </summary>
        public static string SaturnExport_DiffBeyond {
            get {
                return ResourceManager.GetString("SaturnExport_DiffBeyond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert Diff.
        /// </summary>
        public static string SaturnExport_DiffExpert {
            get {
                return ResourceManager.GetString("SaturnExport_DiffExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Diff.
        /// </summary>
        public static string SaturnExport_DiffHard {
            get {
                return ResourceManager.GetString("SaturnExport_DiffHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inferno Diff.
        /// </summary>
        public static string SaturnExport_DiffInferno {
            get {
                return ResourceManager.GetString("SaturnExport_DiffInferno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Diff.
        /// </summary>
        public static string SaturnExport_DiffNormal {
            get {
                return ResourceManager.GetString("SaturnExport_DiffNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Folder.
        /// </summary>
        public static string SaturnExport_Folder {
            get {
                return ResourceManager.GetString("SaturnExport_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string SaturnExport_Genre {
            get {
                return ResourceManager.GetString("SaturnExport_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jacket.
        /// </summary>
        public static string SaturnExport_Jacket {
            get {
                return ResourceManager.GetString("SaturnExport_Jacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string SaturnExport_Music {
            get {
                return ResourceManager.GetString("SaturnExport_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubi.
        /// </summary>
        public static string SaturnExport_Rubi {
            get {
                return ResourceManager.GetString("SaturnExport_Rubi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string SaturnExport_Title {
            get {
                return ResourceManager.GetString("SaturnExport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Saturn Folder.
        /// </summary>
        public static string SaturnExport_WindowTitle {
            get {
                return ResourceManager.GetString("SaturnExport_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitsound Offset.
        /// </summary>
        public static string Settings_Audio_HitsoundOffset {
            get {
                return ResourceManager.GetString("Settings_Audio_HitsoundOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitsound Volume.
        /// </summary>
        public static string Settings_Audio_HitsoundVolume {
            get {
                return ResourceManager.GetString("Settings_Audio_HitsoundVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Volume.
        /// </summary>
        public static string Settings_Audio_MusicVolume {
            get {
                return ResourceManager.GetString("Settings_Audio_MusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat Division.
        /// </summary>
        public static string Settings_BeatDivision {
            get {
                return ResourceManager.GetString("Settings_BeatDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle Ticks.
        /// </summary>
        public static string Settings_Color_AngleTicks {
            get {
                return ResourceManager.GetString("Settings_Color_AngleTicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Far.
        /// </summary>
        public static string Settings_Color_BackgroundFar {
            get {
                return ResourceManager.GetString("Settings_Color_BackgroundFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Near.
        /// </summary>
        public static string Settings_Color_BackgroundNear {
            get {
                return ResourceManager.GetString("Settings_Color_BackgroundNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background [No Mask].
        /// </summary>
        public static string Settings_Color_BackgroundNoMask {
            get {
                return ResourceManager.GetString("Settings_Color_BackgroundNoMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat Line.
        /// </summary>
        public static string Settings_Color_BeatLine {
            get {
                return ResourceManager.GetString("Settings_Color_BeatLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide Lines.
        /// </summary>
        public static string Settings_Color_GuideLines {
            get {
                return ResourceManager.GetString("Settings_Color_GuideLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judgement Line Primary.
        /// </summary>
        public static string Settings_Color_JudgementLinePrimary {
            get {
                return ResourceManager.GetString("Settings_Color_JudgementLinePrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judgement Line Secondary.
        /// </summary>
        public static string Settings_Color_JudgementLineSecondary {
            get {
                return ResourceManager.GetString("Settings_Color_JudgementLineSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Line.
        /// </summary>
        public static string Settings_Color_MeasureLine {
            get {
                return ResourceManager.GetString("Settings_Color_MeasureLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string Settings_Color_Sync {
            get {
                return ResourceManager.GetString("Settings_Color_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Placed Note.
        /// </summary>
        public static string Settings_Editor_HighlightPlacedNote {
            get {
                return ResourceManager.GetString("Settings_Editor_HighlightPlacedNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantize on Pause.
        /// </summary>
        public static string Settings_Editor_QuantizeOnPause {
            get {
                return ResourceManager.GetString("Settings_Editor_QuantizeOnPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide Line Type.
        /// </summary>
        public static string Settings_GuideLineType {
            get {
                return ResourceManager.GetString("Settings_GuideLineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Settings_Header_Appearance {
            get {
                return ResourceManager.GetString("Settings_Header_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Settings_Header_Audio {
            get {
                return ResourceManager.GetString("Settings_Header_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string Settings_Header_Colors {
            get {
                return ResourceManager.GetString("Settings_Header_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string Settings_Header_Editor {
            get {
                return ResourceManager.GetString("Settings_Header_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gimmicks.
        /// </summary>
        public static string Settings_Header_Gimmicks {
            get {
                return ResourceManager.GetString("Settings_Header_Gimmicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keymap.
        /// </summary>
        public static string Settings_Header_Keymap {
            get {
                return ResourceManager.GetString("Settings_Header_Keymap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering.
        /// </summary>
        public static string Settings_Header_Rendering {
            get {
                return ResourceManager.GetString("Settings_Header_Rendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Hitsound.
        /// </summary>
        public static string Settings_Hitsound_Bonus {
            get {
                return ResourceManager.GetString("Settings_Hitsound_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide Hitsound.
        /// </summary>
        public static string Settings_Hitsound_Guide {
            get {
                return ResourceManager.GetString("Settings_Hitsound_Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R-Note Hitsound.
        /// </summary>
        public static string Settings_Hitsound_RNote {
            get {
                return ResourceManager.GetString("Settings_Hitsound_RNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe Hitsound.
        /// </summary>
        public static string Settings_Hitsound_Swipe {
            get {
                return ResourceManager.GetString("Settings_Hitsound_Swipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch Hitsound.
        /// </summary>
        public static string Settings_Hitsound_Touch {
            get {
                return ResourceManager.GetString("Settings_Hitsound_Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Render Method.
        /// </summary>
        public static string Settings_HoldRenderMethod {
            get {
                return ResourceManager.GetString("Settings_HoldRenderMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Note Speed.
        /// </summary>
        public static string Settings_Keymap_DecreaseNoteSpeed {
            get {
                return ResourceManager.GetString("Settings_Keymap_DecreaseNoteSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Note Speed.
        /// </summary>
        public static string Settings_Keymap_IncreaseNoteSpeed {
            get {
                return ResourceManager.GetString("Settings_Keymap_IncreaseNoteSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Selection 1.
        /// </summary>
        public static string Settings_Keymap_TypeRadio1 {
            get {
                return ResourceManager.GetString("Settings_Keymap_TypeRadio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Selection 2.
        /// </summary>
        public static string Settings_Keymap_TypeRadio2 {
            get {
                return ResourceManager.GetString("Settings_Keymap_TypeRadio2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Selection 3.
        /// </summary>
        public static string Settings_Keymap_TypeRadio3 {
            get {
                return ResourceManager.GetString("Settings_Keymap_TypeRadio3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for input....
        /// </summary>
        public static string Settings_Keymap_WaitingForInput {
            get {
                return ResourceManager.GetString("Settings_Keymap_WaitingForInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Thickness.
        /// </summary>
        public static string Settings_NoteSize {
            get {
                return ResourceManager.GetString("Settings_NoteSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Speed.
        /// </summary>
        public static string Settings_NoteSpeed {
            get {
                return ResourceManager.GetString("Settings_NoteSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Rate [Hz].
        /// </summary>
        public static string Settings_RefreshRate {
            get {
                return ResourceManager.GetString("Settings_RefreshRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert to Default Settings.
        /// </summary>
        public static string Settings_RevertToDefault {
            get {
                return ResourceManager.GetString("Settings_RevertToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to revert your Settings?.
        /// </summary>
        public static string Settings_RevertWarning {
            get {
                return ResourceManager.GetString("Settings_RevertWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Chain Stripes.
        /// </summary>
        public static string Settings_ShowChainStripes {
            get {
                return ResourceManager.GetString("Settings_ShowChainStripes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Gimmick Notes during Playback.
        /// </summary>
        public static string Settings_ShowGimmickNotesDuringPlayback {
            get {
                return ResourceManager.GetString("Settings_ShowGimmickNotesDuringPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Mask Notes during Playback.
        /// </summary>
        public static string Settings_ShowMaskDuringPlayback {
            get {
                return ResourceManager.GetString("Settings_ShowMaskDuringPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Speed Changes.
        /// </summary>
        public static string Settings_ShowSpeedChanges {
            get {
                return ResourceManager.GetString("Settings_ShowSpeedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will quantize all notes to common beat divisions to fix errors like a note on [0 1919] instead of [1 0].
        ///
        ///Continue?.
        /// </summary>
        public static string Tools_FixOffByOneDescription {
            get {
                return ResourceManager.GetString("Tools_FixOffByOneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix off-by-one Error.
        /// </summary>
        public static string Tools_FixOffByOneTitle {
            get {
                return ResourceManager.GetString("Tools_FixOffByOneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator Type.
        /// </summary>
        public static string Tools_GeneratorType {
            get {
                return ResourceManager.GetString("Tools_GeneratorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval [Beat Division].
        /// </summary>
        public static string Tools_Interval {
            get {
                return ResourceManager.GetString("Tools_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Edge.
        /// </summary>
        public static string Tools_Jagged_LeftEdge {
            get {
                return ResourceManager.GetString("Tools_Jagged_LeftEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Edge [Max].
        /// </summary>
        public static string Tools_Jagged_LeftEdgeMax {
            get {
                return ResourceManager.GetString("Tools_Jagged_LeftEdgeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Edge [Min].
        /// </summary>
        public static string Tools_Jagged_LeftEdgeMin {
            get {
                return ResourceManager.GetString("Tools_Jagged_LeftEdgeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise.
        /// </summary>
        public static string Tools_Jagged_Noise {
            get {
                return ResourceManager.GetString("Tools_Jagged_Noise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset Even Index.
        /// </summary>
        public static string Tools_Jagged_OffsetEven {
            get {
                return ResourceManager.GetString("Tools_Jagged_OffsetEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Edge.
        /// </summary>
        public static string Tools_Jagged_RightEdge {
            get {
                return ResourceManager.GetString("Tools_Jagged_RightEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Edge [Max].
        /// </summary>
        public static string Tools_Jagged_RightEdgeMax {
            get {
                return ResourceManager.GetString("Tools_Jagged_RightEdgeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Edge [Min].
        /// </summary>
        public static string Tools_Jagged_RightEdgeMin {
            get {
                return ResourceManager.GetString("Tools_Jagged_RightEdgeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spikes.
        /// </summary>
        public static string Tools_Jagged_Spikes {
            get {
                return ResourceManager.GetString("Tools_Jagged_Spikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold to Chain.
        /// </summary>
        public static string Tools_Reconstruct_HoldToChain {
            get {
                return ResourceManager.GetString("Tools_Reconstruct_HoldToChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold to Hold.
        /// </summary>
        public static string Tools_Reconstruct_HoldToHold {
            get {
                return ResourceManager.GetString("Tools_Reconstruct_HoldToHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift by.
        /// </summary>
        public static string Tools_ShiftBy {
            get {
                return ResourceManager.GetString("Tools_ShiftBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserts Hold segments in front of the selected segment..
        /// </summary>
        public static string ToolTip_BakeHold {
            get {
                return ResourceManager.GetString("ToolTip_BakeHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Note [extra clear points, sparkly sound].
        /// </summary>
        public static string ToolTip_BonusType_Bonus {
            get {
                return ResourceManager.GetString("ToolTip_BonusType_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Note [no effects].
        /// </summary>
        public static string ToolTip_BonusType_None {
            get {
                return ResourceManager.GetString("ToolTip_BonusType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R-Note [worth double, rainbow effect, loud splash sound].
        /// </summary>
        public static string ToolTip_BonusType_RNote {
            get {
                return ResourceManager.GetString("ToolTip_BonusType_RNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserts a BPM change..
        /// </summary>
        public static string ToolTip_BPM {
            get {
                return ResourceManager.GetString("ToolTip_BPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info about a chart, such as the audio, author and level..
        /// </summary>
        public static string ToolTip_ChartInfo {
            get {
                return ResourceManager.GetString("ToolTip_ChartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit both Shape and Type at once..
        /// </summary>
        public static string ToolTip_EditBoth {
            get {
                return ResourceManager.GetString("ToolTip_EditBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight any Note of a Hold, then click [Edit Hold] to continue editing where you left off..
        /// </summary>
        public static string ToolTip_EditHold {
            get {
                return ResourceManager.GetString("ToolTip_EditHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Note Size and Position..
        /// </summary>
        public static string ToolTip_EditShape {
            get {
                return ResourceManager.GetString("ToolTip_EditShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Note Type and Bonus Type..
        /// </summary>
        public static string ToolTip_EditType {
            get {
                return ResourceManager.GetString("ToolTip_EditType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically highlights a Note after placing it..
        /// </summary>
        public static string ToolTip_HighlightPlacedNote {
            get {
                return ResourceManager.GetString("ToolTip_HighlightPlacedNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserts a HiSpeed change. [aka. Scroll Speed / Soflan].
        /// </summary>
        public static string ToolTip_HiSpeed {
            get {
                return ResourceManager.GetString("ToolTip_HiSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options for differently shaped Hold Notes. Just try them out to see :].
        /// </summary>
        public static string ToolTip_HoldEase {
            get {
                return ResourceManager.GetString("ToolTip_HoldEase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original rendering method that draws holds segment-by-segment. Bad performance, but technically more mature..
        /// </summary>
        public static string ToolTip_HoldRender_Legacy {
            get {
                return ResourceManager.GetString("ToolTip_HoldRender_Legacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performs better than the original by batching all segments into one shape, saving dozens, if not hundreds of calls to SkiaSharp. Also fixes the tv-static-looking seams on dense holds..
        /// </summary>
        public static string ToolTip_HoldRender_Modern {
            get {
                return ResourceManager.GetString("ToolTip_HoldRender_Modern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserts a Note at the current timestamp, with the currently selected properties..
        /// </summary>
        public static string ToolTip_Insert {
            get {
                return ResourceManager.GetString("ToolTip_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserts a single Hold segment at the current timestamp. Highlight any segment to specify which Hold to insert it in..
        /// </summary>
        public static string ToolTip_InsertHold {
            get {
                return ResourceManager.GetString("ToolTip_InsertHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Gimmick Markers..
        /// </summary>
        public static string ToolTip_LayerGimmick {
            get {
                return ResourceManager.GetString("ToolTip_LayerGimmick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Mask Notes..
        /// </summary>
        public static string ToolTip_LayerMask {
            get {
                return ResourceManager.GetString("ToolTip_LayerMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Playable Notes..
        /// </summary>
        public static string ToolTip_LayerNote {
            get {
                return ResourceManager.GetString("ToolTip_LayerNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask Animation will propagate from the center of the Note outwards..
        /// </summary>
        public static string ToolTip_MaskDirection_Center {
            get {
                return ResourceManager.GetString("ToolTip_MaskDirection_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask Animation will propagate from one edge of the Note to the other Clockwise..
        /// </summary>
        public static string ToolTip_MaskDirection_Clockwise {
            get {
                return ResourceManager.GetString("ToolTip_MaskDirection_Clockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask Animation will propagate from one edge of the Note to the other Counterclockwise..
        /// </summary>
        public static string ToolTip_MaskDirection_CounterClockwise {
            get {
                return ResourceManager.GetString("ToolTip_MaskDirection_CounterClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror Notes around the mirror axis. Hover over the number to see the axis..
        /// </summary>
        public static string ToolTip_Mirror {
            get {
                return ResourceManager.GetString("ToolTip_Mirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gimmick-related functions..
        /// </summary>
        public static string ToolTip_ModifyGimmicks {
            get {
                return ResourceManager.GetString("ToolTip_ModifyGimmicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note-related functions, like Edit and Delete..
        /// </summary>
        public static string ToolTip_ModifyNotes {
            get {
                return ResourceManager.GetString("ToolTip_ModifyNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight the nearest Note to the current timestamp..
        /// </summary>
        public static string ToolTip_Nearest {
            get {
                return ResourceManager.GetString("ToolTip_Nearest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight the next Note..
        /// </summary>
        public static string ToolTip_Next {
            get {
                return ResourceManager.GetString("ToolTip_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently selected NoteType..
        /// </summary>
        public static string ToolTip_NoteTypes {
            get {
                return ResourceManager.GetString("ToolTip_NoteTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust playback speed..
        /// </summary>
        public static string ToolTip_PlaybackSpeed {
            get {
                return ResourceManager.GetString("ToolTip_PlaybackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/Pause.
        /// </summary>
        public static string ToolTip_PlayPause {
            get {
                return ResourceManager.GetString("ToolTip_PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight the previous Note..
        /// </summary>
        public static string ToolTip_Previous {
            get {
                return ResourceManager.GetString("ToolTip_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantizes the playhead to the current beat division when pausing..
        /// </summary>
        public static string ToolTip_QuantizeOnPause {
            get {
                return ResourceManager.GetString("ToolTip_QuantizeOnPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick access to some commonly changed settings..
        /// </summary>
        public static string ToolTip_QuickSettings {
            get {
                return ResourceManager.GetString("ToolTip_QuickSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserts a Reverse Effect that scrolls Notes backwards for a set amount of time. [not rendered yet].
        /// </summary>
        public static string ToolTip_Reverse {
            get {
                return ResourceManager.GetString("ToolTip_Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes stop scrolling backwards and scroll forwards again from this point..
        /// </summary>
        public static string ToolTip_Reverse_EffectEnd {
            get {
                return ResourceManager.GetString("ToolTip_Reverse_EffectEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes begin scrolling backwards from this point..
        /// </summary>
        public static string ToolTip_Reverse_EffectStart {
            get {
                return ResourceManager.GetString("ToolTip_Reverse_EffectStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Notes between this timestamp and [Effect End] are scrolled backwards..
        /// </summary>
        public static string ToolTip_Reverse_NoteZoneEnd {
            get {
                return ResourceManager.GetString("ToolTip_Reverse_NoteZoneEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info about selection and highlighting..
        /// </summary>
        public static string ToolTip_SelectionInfo {
            get {
                return ResourceManager.GetString("ToolTip_SelectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the render flag on a Hold Note to false. This means the game will ignore it when generating the visuals for a Hold Note, smoothing out any irregular size/position changes. Judgement still follows the segments!.
        /// </summary>
        public static string ToolTip_SetRenderFalse {
            get {
                return ResourceManager.GetString("ToolTip_SetRenderFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the render flag on a Hold Note to true. See [Set Render False] for more info..
        /// </summary>
        public static string ToolTip_SetRenderTrue {
            get {
                return ResourceManager.GetString("ToolTip_SetRenderTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connects the end of a Hold Note to the start of another to stitch them into one. Must select ONLY a Hold End and a Hold Start..
        /// </summary>
        public static string ToolTip_StitchHold {
            get {
                return ResourceManager.GetString("ToolTip_StitchHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserts a Stop Effect that freezes Note scroll between Start and End..
        /// </summary>
        public static string ToolTip_Stop {
            get {
                return ResourceManager.GetString("ToolTip_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserts a Time Signature change..
        /// </summary>
        public static string ToolTip_TimeSignature {
            get {
                return ResourceManager.GetString("ToolTip_TimeSignature", resourceCulture);
            }
        }
    }
}
