//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercuryMapper.Assets.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MercuryMapper.Assets.Lang.Resources.de-DE", typeof(Resources_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        public static string BonusType_Bonus {
            get {
                return ResourceManager.GetString("BonusType_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Bonus.
        /// </summary>
        public static string BonusType_None {
            get {
                return ResourceManager.GetString("BonusType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R-Note.
        /// </summary>
        public static string BonusType_RNote {
            get {
                return ResourceManager.GetString("BonusType_RNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpret.
        /// </summary>
        public static string ChartProperties_Artist {
            get {
                return ResourceManager.GetString("ChartProperties_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Author.
        /// </summary>
        public static string ChartProperties_Author {
            get {
                return ResourceManager.GetString("ChartProperties_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM.
        /// </summary>
        public static string ChartProperties_Bpm {
            get {
                return ResourceManager.GetString("ChartProperties_Bpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Schwelle.
        /// </summary>
        public static string ChartProperties_ClearThreshold {
            get {
                return ResourceManager.GetString("ChartProperties_ClearThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string ChartProperties_Level {
            get {
                return ResourceManager.GetString("ChartProperties_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Offset.
        /// </summary>
        public static string ChartProperties_MovieOffset {
            get {
                return ResourceManager.GetString("ChartProperties_MovieOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musik Dateipfad.
        /// </summary>
        public static string ChartProperties_MusicFilePath {
            get {
                return ResourceManager.GetString("ChartProperties_MusicFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string ChartProperties_Offset {
            get {
                return ResourceManager.GetString("ChartProperties_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorschau Länge.
        /// </summary>
        public static string ChartProperties_PreviewLength {
            get {
                return ResourceManager.GetString("ChartProperties_PreviewLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorschau Start.
        /// </summary>
        public static string ChartProperties_PreviewTime {
            get {
                return ResourceManager.GetString("ChartProperties_PreviewTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taktart.
        /// </summary>
        public static string ChartProperties_TimeSignature {
            get {
                return ResourceManager.GetString("ChartProperties_TimeSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        public static string ChartProperties_Title {
            get {
                return ResourceManager.GetString("ChartProperties_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gimmick Hinzufügen.
        /// </summary>
        public static string Editor_AddGimmick {
            get {
                return ResourceManager.GetString("Editor_AddGimmick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Note Vorberechnen.
        /// </summary>
        public static string Editor_BakeHold {
            get {
                return ResourceManager.GetString("Editor_BakeHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat.
        /// </summary>
        public static string Editor_Beat {
            get {
                return ResourceManager.GetString("Editor_Beat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiedergabegeschwindigkeit erhöhen.
        /// </summary>
        public static string Editor_DecreasePlaybackSpeed {
            get {
                return ResourceManager.GetString("Editor_DecreasePlaybackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string Editor_Delete {
            get {
                return ResourceManager.GetString("Editor_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gimmick Löschen.
        /// </summary>
        public static string Editor_DeleteGimmick {
            get {
                return ResourceManager.GetString("Editor_DeleteGimmick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswahl Löschen.
        /// </summary>
        public static string Editor_DeleteSelection {
            get {
                return ResourceManager.GetString("Editor_DeleteSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alles Abwählen.
        /// </summary>
        public static string Editor_DeselectAll {
            get {
                return ResourceManager.GetString("Editor_DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gimmick Bearbeiten.
        /// </summary>
        public static string Editor_EditGimmick {
            get {
                return ResourceManager.GetString("Editor_EditGimmick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Bearbeiten.
        /// </summary>
        public static string Editor_EditHold {
            get {
                return ResourceManager.GetString("Editor_EditHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten [Typ].
        /// </summary>
        public static string Editor_EditNoteProperties {
            get {
                return ResourceManager.GetString("Editor_EditNoteProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten [Form].
        /// </summary>
        public static string Editor_EditNoteShape {
            get {
                return ResourceManager.GetString("Editor_EditNoteShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten [Beides].
        /// </summary>
        public static string Editor_EditNoteShapeProperties {
            get {
                return ResourceManager.GetString("Editor_EditNoteShapeProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Beenden.
        /// </summary>
        public static string Editor_EndHold {
            get {
                return ResourceManager.GetString("Editor_EndHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart-Info.
        /// </summary>
        public static string Editor_ExpanderHeader_ChartInfo {
            get {
                return ResourceManager.GetString("Editor_ExpanderHeader_ChartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gimmicks Modifizieren.
        /// </summary>
        public static string Editor_ExpanderHeader_ModifyGimmicks {
            get {
                return ResourceManager.GetString("Editor_ExpanderHeader_ModifyGimmicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noten Modifizieren.
        /// </summary>
        public static string Editor_ExpanderHeader_ModifyNotes {
            get {
                return ResourceManager.GetString("Editor_ExpanderHeader_ModifyNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schnell-Einstellungen.
        /// </summary>
        public static string Editor_ExpanderHeader_QuickSettings {
            get {
                return ResourceManager.GetString("Editor_ExpanderHeader_QuickSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswahl-Info.
        /// </summary>
        public static string Editor_ExpanderHeader_SelectionInfo {
            get {
                return ResourceManager.GetString("Editor_ExpanderHeader_SelectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gimmick-Art.
        /// </summary>
        public static string Editor_GimmickType {
            get {
                return ResourceManager.GetString("Editor_GimmickType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naheste.
        /// </summary>
        public static string Editor_HighlightNearest {
            get {
                return ResourceManager.GetString("Editor_HighlightNearest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nächste &gt;.
        /// </summary>
        public static string Editor_HighlightNext {
            get {
                return ResourceManager.GetString("Editor_HighlightNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nächste Note Hervorheben.
        /// </summary>
        public static string Editor_HighlightNextNote {
            get {
                return ResourceManager.GetString("Editor_HighlightNextNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Vorherige.
        /// </summary>
        public static string Editor_HighlightPrev {
            get {
                return ResourceManager.GetString("Editor_HighlightPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorherige Note Hervorheben.
        /// </summary>
        public static string Editor_HighlightPrevNote {
            get {
                return ResourceManager.GetString("Editor_HighlightPrevNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiedergabegeschwindigkeit verringern.
        /// </summary>
        public static string Editor_IncreasePlaybackSpeed {
            get {
                return ResourceManager.GetString("Editor_IncreasePlaybackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einfügen.
        /// </summary>
        public static string Editor_Insert {
            get {
                return ResourceManager.GetString("Editor_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masken-Richtung.
        /// </summary>
        public static string Editor_MaskDirection {
            get {
                return ResourceManager.GetString("Editor_MaskDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takt.
        /// </summary>
        public static string Editor_Measure {
            get {
                return ResourceManager.GetString("Editor_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiegel-Achse.
        /// </summary>
        public static string Editor_MirrorAxis {
            get {
                return ResourceManager.GetString("Editor_MirrorAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiegeln.
        /// </summary>
        public static string Editor_MirrorNote {
            get {
                return ResourceManager.GetString("Editor_MirrorNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Chart.
        /// </summary>
        public static string Editor_NewChart {
            get {
                return ResourceManager.GetString("Editor_NewChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die ausgewählte Audiodatei konnte nicht gefunden werden..
        /// </summary>
        public static string Editor_NewChartInvalidAudio {
            get {
                return ResourceManager.GetString("Editor_NewChartInvalidAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart hat ungültige BPM. BPM muss über Null liegen..
        /// </summary>
        public static string Editor_NewChartInvalidBpm {
            get {
                return ResourceManager.GetString("Editor_NewChartInvalidBpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart hat ungültige Taktart. Upper und Lower müssen über Null liegen..
        /// </summary>
        public static string Editor_NewChartInvalidTimeSig {
            get {
                return ResourceManager.GetString("Editor_NewChartInvalidTimeSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noten Kappen.
        /// </summary>
        public static string Editor_NoteCaps {
            get {
                return ResourceManager.GetString("Editor_NoteCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noten-Art.
        /// </summary>
        public static string Editor_NoteType {
            get {
                return ResourceManager.GetString("Editor_NoteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Editor_Pause {
            get {
                return ResourceManager.GetString("Editor_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Editor_Play {
            get {
                return ResourceManager.GetString("Editor_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Editor_Position {
            get {
                return ResourceManager.GetString("Editor_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position - [Quick Edit].
        /// </summary>
        public static string Editor_QuickEditDecreasePosition {
            get {
                return ResourceManager.GetString("Editor_QuickEditDecreasePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size - [Quick Edit].
        /// </summary>
        public static string Editor_QuickEditDecreaseSize {
            get {
                return ResourceManager.GetString("Editor_QuickEditDecreaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp - [Quick Edit].
        /// </summary>
        public static string Editor_QuickEditDecreaseTimestamp {
            get {
                return ResourceManager.GetString("Editor_QuickEditDecreaseTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position + [Quick Edit].
        /// </summary>
        public static string Editor_QuickEditIncreasePosition {
            get {
                return ResourceManager.GetString("Editor_QuickEditIncreasePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size + [Quick Edit].
        /// </summary>
        public static string Editor_QuickEditIncreaseSize {
            get {
                return ResourceManager.GetString("Editor_QuickEditIncreaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp + [Quick Edit].
        /// </summary>
        public static string Editor_QuickEditIncreaseTimestamp {
            get {
                return ResourceManager.GetString("Editor_QuickEditIncreaseTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alles Auswählen.
        /// </summary>
        public static string Editor_SelectAll {
            get {
                return ResourceManager.GetString("Editor_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hervorgehobene Note Auswählen.
        /// </summary>
        public static string Editor_SelectHighlightedNote {
            get {
                return ResourceManager.GetString("Editor_SelectHighlightedNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgewählte Noten.
        /// </summary>
        public static string Editor_SelectionInfo_SelectedNotes {
            get {
                return ResourceManager.GetString("Editor_SelectionInfo_SelectedNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Größe.
        /// </summary>
        public static string Editor_Size {
            get {
                return ResourceManager.GetString("Editor_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string Generic_Close {
            get {
                return ResourceManager.GetString("Generic_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen.
        /// </summary>
        public static string Generic_Create {
            get {
                return ResourceManager.GetString("Generic_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audiodatei nicht gefunden..
        /// </summary>
        public static string Generic_InvalidAudioWarning {
            get {
                return ResourceManager.GetString("Generic_InvalidAudioWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string Generic_No {
            get {
                return ResourceManager.GetString("Generic_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine.
        /// </summary>
        public static string Generic_None {
            get {
                return ResourceManager.GetString("Generic_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Generic_Ok {
            get {
                return ResourceManager.GetString("Generic_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern und Schließen.
        /// </summary>
        public static string Generic_SaveAndClose {
            get {
                return ResourceManager.GetString("Generic_SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart ist nicht gespeichert. Möchten Sie speichern?.
        /// </summary>
        public static string Generic_SaveWarning {
            get {
                return ResourceManager.GetString("Generic_SaveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart hat entweder kein Audio oder die angegebene Audiodatei wurde nicht gefunden.
        ///Möchten Sie eine Datei manuell auswählen?.
        /// </summary>
        public static string Generic_SelectAudioPrompt {
            get {
                return ResourceManager.GetString("Generic_SelectAudioPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei Auswählen.
        /// </summary>
        public static string Generic_SelectFile {
            get {
                return ResourceManager.GetString("Generic_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string Generic_Yes {
            get {
                return ResourceManager.GetString("Generic_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM.
        /// </summary>
        public static string Gimmick_BpmChange {
            get {
                return ResourceManager.GetString("Gimmick_BpmChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HiSpeed.
        /// </summary>
        public static string Gimmick_HiSpeedChange {
            get {
                return ResourceManager.GetString("Gimmick_HiSpeedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        public static string Gimmick_Reverse {
            get {
                return ResourceManager.GetString("Gimmick_Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Effekt Ende.
        /// </summary>
        public static string Gimmick_ReverseEffectEnd {
            get {
                return ResourceManager.GetString("Gimmick_ReverseEffectEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Effekt Anfang.
        /// </summary>
        public static string Gimmick_ReverseEffectStart {
            get {
                return ResourceManager.GetString("Gimmick_ReverseEffectStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Noten-Zone Ende.
        /// </summary>
        public static string Gimmick_ReverseNoteEnd {
            get {
                return ResourceManager.GetString("Gimmick_ReverseNoteEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopp.
        /// </summary>
        public static string Gimmick_Stop {
            get {
                return ResourceManager.GetString("Gimmick_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopp Ende.
        /// </summary>
        public static string Gimmick_StopEnd {
            get {
                return ResourceManager.GetString("Gimmick_StopEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopp Anfang.
        /// </summary>
        public static string Gimmick_StopStart {
            get {
                return ResourceManager.GetString("Gimmick_StopStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taktart.
        /// </summary>
        public static string Gimmick_TimeSigChange {
            get {
                return ResourceManager.GetString("Gimmick_TimeSigChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von Mitte.
        /// </summary>
        public static string MaskDirection_Center {
            get {
                return ResourceManager.GetString("MaskDirection_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Uhrzeigersinn.
        /// </summary>
        public static string MaskDirection_Clockwise {
            get {
                return ResourceManager.GetString("MaskDirection_Clockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gegen Uhrzeigersinn.
        /// </summary>
        public static string MaskDirection_Counterclockwise {
            get {
                return ResourceManager.GetString("MaskDirection_Counterclockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopieren.
        /// </summary>
        public static string Menu_Copy {
            get {
                return ResourceManager.GetString("Menu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausschneiden.
        /// </summary>
        public static string Menu_Cut {
            get {
                return ResourceManager.GetString("Menu_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportieren.
        /// </summary>
        public static string Menu_Export {
            get {
                return ResourceManager.GetString("Menu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportieren für Mercury.
        /// </summary>
        public static string Menu_ExportMercury {
            get {
                return ResourceManager.GetString("Menu_ExportMercury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportieren für Saturn.
        /// </summary>
        public static string Menu_ExportSaturn {
            get {
                return ResourceManager.GetString("Menu_ExportSaturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu.
        /// </summary>
        public static string Menu_New {
            get {
                return ResourceManager.GetString("Menu_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen.
        /// </summary>
        public static string Menu_Open {
            get {
                return ResourceManager.GetString("Menu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einfügen.
        /// </summary>
        public static string Menu_Paste {
            get {
                return ResourceManager.GetString("Menu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederholen.
        /// </summary>
        public static string Menu_Redo {
            get {
                return ResourceManager.GetString("Menu_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern Als.
        /// </summary>
        public static string Menu_SaveAs {
            get {
                return ResourceManager.GetString("Menu_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rückgängig.
        /// </summary>
        public static string Menu_Undo {
            get {
                return ResourceManager.GetString("Menu_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string MenuHeader_Edit {
            get {
                return ResourceManager.GetString("MenuHeader_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei.
        /// </summary>
        public static string MenuHeader_File {
            get {
                return ResourceManager.GetString("MenuHeader_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswählen.
        /// </summary>
        public static string MenuHeader_Select {
            get {
                return ResourceManager.GetString("MenuHeader_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kette.
        /// </summary>
        public static string Note_Chain {
            get {
                return ResourceManager.GetString("Note_Chain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Ende.
        /// </summary>
        public static string Note_EndOfChart {
            get {
                return ResourceManager.GetString("Note_EndOfChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markieren.
        /// </summary>
        public static string Note_Highlight {
            get {
                return ResourceManager.GetString("Note_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halten.
        /// </summary>
        public static string Note_Hold {
            get {
                return ResourceManager.GetString("Note_Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halte-Ende.
        /// </summary>
        public static string Note_HoldEnd {
            get {
                return ResourceManager.GetString("Note_HoldEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halte-Segment.
        /// </summary>
        public static string Note_HoldSegment {
            get {
                return ResourceManager.GetString("Note_HoldSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halte-Start.
        /// </summary>
        public static string Note_HoldStart {
            get {
                return ResourceManager.GetString("Note_HoldStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haltefläche Fern.
        /// </summary>
        public static string Note_HoldSurfaceFar {
            get {
                return ResourceManager.GetString("Note_HoldSurfaceFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haltefläche Nah.
        /// </summary>
        public static string Note_HoldSurfaceNear {
            get {
                return ResourceManager.GetString("Note_HoldSurfaceNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maske Hinzufügen.
        /// </summary>
        public static string Note_MaskAdd {
            get {
                return ResourceManager.GetString("Note_MaskAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maske Entfernen.
        /// </summary>
        public static string Note_MaskRemove {
            get {
                return ResourceManager.GetString("Note_MaskRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswahl.
        /// </summary>
        public static string Note_Selection {
            get {
                return ResourceManager.GetString("Note_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↩ Wischen (mit Uhr).
        /// </summary>
        public static string Note_SlideClockwise {
            get {
                return ResourceManager.GetString("Note_SlideClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↪ Wischen (gegen Uhr).
        /// </summary>
        public static string Note_SlideCounterclockwise {
            get {
                return ResourceManager.GetString("Note_SlideCounterclockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↓ Schieben (rückwärts).
        /// </summary>
        public static string Note_SnapBackward {
            get {
                return ResourceManager.GetString("Note_SnapBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↑ Schieben (vorwärts).
        /// </summary>
        public static string Note_SnapForward {
            get {
                return ResourceManager.GetString("Note_SnapForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tippen.
        /// </summary>
        public static string Note_Touch {
            get {
                return ResourceManager.GetString("Note_Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitsound Lautstärke.
        /// </summary>
        public static string Settings_Audio_HitsoundVolume {
            get {
                return ResourceManager.GetString("Settings_Audio_HitsoundVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musik Lautstärke.
        /// </summary>
        public static string Settings_Audio_MusicVolume {
            get {
                return ResourceManager.GetString("Settings_Audio_MusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat Unterteilung.
        /// </summary>
        public static string Settings_BeatDivision {
            get {
                return ResourceManager.GetString("Settings_BeatDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winkel-Striche.
        /// </summary>
        public static string Settings_Color_AngleTicks {
            get {
                return ResourceManager.GetString("Settings_Color_AngleTicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hintergrund Fern.
        /// </summary>
        public static string Settings_Color_BackgroundFar {
            get {
                return ResourceManager.GetString("Settings_Color_BackgroundFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hintergrund Nah.
        /// </summary>
        public static string Settings_Color_BackgroundNear {
            get {
                return ResourceManager.GetString("Settings_Color_BackgroundNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hintergrund [Ohne Maske].
        /// </summary>
        public static string Settings_Color_BackgroundNoMask {
            get {
                return ResourceManager.GetString("Settings_Color_BackgroundNoMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat-Ring.
        /// </summary>
        public static string Settings_Color_BeatLine {
            get {
                return ResourceManager.GetString("Settings_Color_BeatLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leitlinien.
        /// </summary>
        public static string Settings_Color_GuideLines {
            get {
                return ResourceManager.GetString("Settings_Color_GuideLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wertungslinie Primär.
        /// </summary>
        public static string Settings_Color_JudgementLinePrimary {
            get {
                return ResourceManager.GetString("Settings_Color_JudgementLinePrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wertungslinie Sekundär.
        /// </summary>
        public static string Settings_Color_JudgementLineSecondary {
            get {
                return ResourceManager.GetString("Settings_Color_JudgementLineSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takt-Ring.
        /// </summary>
        public static string Settings_Color_MeasureLine {
            get {
                return ResourceManager.GetString("Settings_Color_MeasureLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string Settings_Color_Sync {
            get {
                return ResourceManager.GetString("Settings_Color_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leitlinien-Typ.
        /// </summary>
        public static string Settings_GuideLineType {
            get {
                return ResourceManager.GetString("Settings_GuideLineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erscheinungsbild.
        /// </summary>
        public static string Settings_Header_Appearance {
            get {
                return ResourceManager.GetString("Settings_Header_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Settings_Header_Audio {
            get {
                return ResourceManager.GetString("Settings_Header_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farben.
        /// </summary>
        public static string Settings_Header_Colors {
            get {
                return ResourceManager.GetString("Settings_Header_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string Settings_Header_Editor {
            get {
                return ResourceManager.GetString("Settings_Header_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gimmicks.
        /// </summary>
        public static string Settings_Header_Gimmicks {
            get {
                return ResourceManager.GetString("Settings_Header_Gimmicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tastaturbelegung.
        /// </summary>
        public static string Settings_Header_Keymap {
            get {
                return ResourceManager.GetString("Settings_Header_Keymap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering.
        /// </summary>
        public static string Settings_Header_Rendering {
            get {
                return ResourceManager.GetString("Settings_Header_Rendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Hitsound.
        /// </summary>
        public static string Settings_Hitsound_Bonus {
            get {
                return ResourceManager.GetString("Settings_Hitsound_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide Hitsound.
        /// </summary>
        public static string Settings_Hitsound_Guide {
            get {
                return ResourceManager.GetString("Settings_Hitsound_Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R-Note Hitsound.
        /// </summary>
        public static string Settings_Hitsound_RNote {
            get {
                return ResourceManager.GetString("Settings_Hitsound_RNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisch Hitsound.
        /// </summary>
        public static string Settings_Hitsound_Swipe {
            get {
                return ResourceManager.GetString("Settings_Hitsound_Swipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip Hitsound.
        /// </summary>
        public static string Settings_Hitsound_Touch {
            get {
                return ResourceManager.GetString("Settings_Hitsound_Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noten-Geschwindigkeit verringern.
        /// </summary>
        public static string Settings_Keymap_DecreaseNoteSpeed {
            get {
                return ResourceManager.GetString("Settings_Keymap_DecreaseNoteSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noten-Geschwindigkeit erhöhen.
        /// </summary>
        public static string Settings_Keymap_IncreaseNoteSpeed {
            get {
                return ResourceManager.GetString("Settings_Keymap_IncreaseNoteSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ-Auswahl 1.
        /// </summary>
        public static string Settings_Keymap_TypeRadio1 {
            get {
                return ResourceManager.GetString("Settings_Keymap_TypeRadio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ-Auswahl 2.
        /// </summary>
        public static string Settings_Keymap_TypeRadio2 {
            get {
                return ResourceManager.GetString("Settings_Keymap_TypeRadio2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ-Auswahl 3.
        /// </summary>
        public static string Settings_Keymap_TypeRadio3 {
            get {
                return ResourceManager.GetString("Settings_Keymap_TypeRadio3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warte auf Eingabe....
        /// </summary>
        public static string Settings_Keymap_WaitingForInput {
            get {
                return ResourceManager.GetString("Settings_Keymap_WaitingForInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noten-Größe.
        /// </summary>
        public static string Settings_NoteSize {
            get {
                return ResourceManager.GetString("Settings_NoteSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noten-Geschwindigkeit.
        /// </summary>
        public static string Settings_NoteSpeed {
            get {
                return ResourceManager.GetString("Settings_NoteSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildwiederholrate [Hz].
        /// </summary>
        public static string Settings_RefreshRate {
            get {
                return ResourceManager.GetString("Settings_RefreshRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf Standard-Einstellungen zurücksetzen.
        /// </summary>
        public static string Settings_RevertToDefault {
            get {
                return ResourceManager.GetString("Settings_RevertToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie Ihre Einstellungen zurücksetzen wollen?.
        /// </summary>
        public static string Settings_RevertWarning {
            get {
                return ResourceManager.GetString("Settings_RevertWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige Gimmick-Noten während Playback.
        /// </summary>
        public static string Settings_ShowGimmickNotesDuringPlayback {
            get {
                return ResourceManager.GetString("Settings_ShowGimmickNotesDuringPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige Maske-Noten während Playback.
        /// </summary>
        public static string Settings_ShowMaskDuringPlayback {
            get {
                return ResourceManager.GetString("Settings_ShowMaskDuringPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige Speed-Changes.
        /// </summary>
        public static string Settings_ShowSpeedChanges {
            get {
                return ResourceManager.GetString("Settings_ShowSpeedChanges", resourceCulture);
            }
        }
    }
}
