//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercuryMapper.Assets.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MercuryMapper.Assets.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        public static string BonusType_Bonus {
            get {
                return ResourceManager.GetString("BonusType_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string BonusType_None {
            get {
                return ResourceManager.GetString("BonusType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Note.
        /// </summary>
        public static string BonusType_RNote {
            get {
                return ResourceManager.GetString("BonusType_RNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Playback Speed.
        /// </summary>
        public static string Editor_DecreasePlaybackSpeed {
            get {
                return ResourceManager.GetString("Editor_DecreasePlaybackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Playback Speed.
        /// </summary>
        public static string Editor_IncreasePlaybackSpeed {
            get {
                return ResourceManager.GetString("Editor_IncreasePlaybackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Editor_Insert {
            get {
                return ResourceManager.GetString("Editor_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Editor_Pause {
            get {
                return ResourceManager.GetString("Editor_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Editor_Play {
            get {
                return ResourceManager.GetString("Editor_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Generic_Close {
            get {
                return ResourceManager.GetString("Generic_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Generic_No {
            get {
                return ResourceManager.GetString("Generic_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Close.
        /// </summary>
        public static string Generic_SaveAndClose {
            get {
                return ResourceManager.GetString("Generic_SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart is unsaved. Would you like to save?.
        /// </summary>
        public static string Generic_SaveWarning {
            get {
                return ResourceManager.GetString("Generic_SaveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Generic_Yes {
            get {
                return ResourceManager.GetString("Generic_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM.
        /// </summary>
        public static string Gimmick_BpmChange {
            get {
                return ResourceManager.GetString("Gimmick_BpmChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HiSpeed.
        /// </summary>
        public static string Gimmick_HiSpeedChange {
            get {
                return ResourceManager.GetString("Gimmick_HiSpeedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        public static string Gimmick_Reverse {
            get {
                return ResourceManager.GetString("Gimmick_Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Gimmick_Stop {
            get {
                return ResourceManager.GetString("Gimmick_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Signature.
        /// </summary>
        public static string Gimmick_TimeSigChange {
            get {
                return ResourceManager.GetString("Gimmick_TimeSigChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Center.
        /// </summary>
        public static string MaskDirection_Center {
            get {
                return ResourceManager.GetString("MaskDirection_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clockwise.
        /// </summary>
        public static string MaskDirection_Clockwise {
            get {
                return ResourceManager.GetString("MaskDirection_Clockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counterclockwise.
        /// </summary>
        public static string MaskDirection_Counterclockwise {
            get {
                return ResourceManager.GetString("MaskDirection_Counterclockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Menu_Copy {
            get {
                return ResourceManager.GetString("Menu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Menu_Cut {
            get {
                return ResourceManager.GetString("Menu_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Menu_Export {
            get {
                return ResourceManager.GetString("Menu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export for Mercury.
        /// </summary>
        public static string Menu_ExportMercury {
            get {
                return ResourceManager.GetString("Menu_ExportMercury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export for Saturn.
        /// </summary>
        public static string Menu_ExportSaturn {
            get {
                return ResourceManager.GetString("Menu_ExportSaturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Menu_New {
            get {
                return ResourceManager.GetString("Menu_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Menu_Open {
            get {
                return ResourceManager.GetString("Menu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Menu_Paste {
            get {
                return ResourceManager.GetString("Menu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Menu_Redo {
            get {
                return ResourceManager.GetString("Menu_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string Menu_SaveAs {
            get {
                return ResourceManager.GetString("Menu_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Menu_Undo {
            get {
                return ResourceManager.GetString("Menu_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MenuHeader_Edit {
            get {
                return ResourceManager.GetString("MenuHeader_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuHeader_File {
            get {
                return ResourceManager.GetString("MenuHeader_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string MenuHeader_Select {
            get {
                return ResourceManager.GetString("MenuHeader_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain.
        /// </summary>
        public static string Note_Chain {
            get {
                return ResourceManager.GetString("Note_Chain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Chart.
        /// </summary>
        public static string Note_EndOfChart {
            get {
                return ResourceManager.GetString("Note_EndOfChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string Note_Highlight {
            get {
                return ResourceManager.GetString("Note_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        public static string Note_Hold {
            get {
                return ResourceManager.GetString("Note_Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold End.
        /// </summary>
        public static string Note_HoldEnd {
            get {
                return ResourceManager.GetString("Note_HoldEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Segment.
        /// </summary>
        public static string Note_HoldSegment {
            get {
                return ResourceManager.GetString("Note_HoldSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Start.
        /// </summary>
        public static string Note_HoldStart {
            get {
                return ResourceManager.GetString("Note_HoldStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Surface Far.
        /// </summary>
        public static string Note_HoldSurfaceFar {
            get {
                return ResourceManager.GetString("Note_HoldSurfaceFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Surface Near.
        /// </summary>
        public static string Note_HoldSurfaceNear {
            get {
                return ResourceManager.GetString("Note_HoldSurfaceNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask Add.
        /// </summary>
        public static string Note_MaskAdd {
            get {
                return ResourceManager.GetString("Note_MaskAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask Remove.
        /// </summary>
        public static string Note_MaskRemove {
            get {
                return ResourceManager.GetString("Note_MaskRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string Note_Selection {
            get {
                return ResourceManager.GetString("Note_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↩ Slide CW.
        /// </summary>
        public static string Note_SlideClockwise {
            get {
                return ResourceManager.GetString("Note_SlideClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↪ Slide CCW.
        /// </summary>
        public static string Note_SlideCounterclockwise {
            get {
                return ResourceManager.GetString("Note_SlideCounterclockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↓ Snap BW.
        /// </summary>
        public static string Note_SnapBackward {
            get {
                return ResourceManager.GetString("Note_SnapBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↑ Snap FW.
        /// </summary>
        public static string Note_SnapForward {
            get {
                return ResourceManager.GetString("Note_SnapForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch.
        /// </summary>
        public static string Note_Touch {
            get {
                return ResourceManager.GetString("Note_Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Settings_Header_Appearance {
            get {
                return ResourceManager.GetString("Settings_Header_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string Settings_Header_Colors {
            get {
                return ResourceManager.GetString("Settings_Header_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string Settings_Header_Editor {
            get {
                return ResourceManager.GetString("Settings_Header_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gimmicks.
        /// </summary>
        public static string Settings_Header_Gimmicks {
            get {
                return ResourceManager.GetString("Settings_Header_Gimmicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keymap.
        /// </summary>
        public static string Settings_Header_Keymap {
            get {
                return ResourceManager.GetString("Settings_Header_Keymap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering.
        /// </summary>
        public static string Settings_Header_Rendering {
            get {
                return ResourceManager.GetString("Settings_Header_Rendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for input....
        /// </summary>
        public static string Settings_Keymap_WaitingForInput {
            get {
                return ResourceManager.GetString("Settings_Keymap_WaitingForInput", resourceCulture);
            }
        }
    }
}
