//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercuryMapper.Assets.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MercuryMapper.Assets.Lang.Resources.de-DE", typeof(Resources_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        public static string BonusType_Bonus {
            get {
                return ResourceManager.GetString("BonusType_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Bonus.
        /// </summary>
        public static string BonusType_None {
            get {
                return ResourceManager.GetString("BonusType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R-Note.
        /// </summary>
        public static string BonusType_RNote {
            get {
                return ResourceManager.GetString("BonusType_RNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Einfügen.
        /// </summary>
        public static string Button_InsertNote {
            get {
                return ResourceManager.GetString("Button_InsertNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM.
        /// </summary>
        public static string Gimmick_BpmChange {
            get {
                return ResourceManager.GetString("Gimmick_BpmChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HiSpeed.
        /// </summary>
        public static string Gimmick_HiSpeedChange {
            get {
                return ResourceManager.GetString("Gimmick_HiSpeedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        public static string Gimmick_Reverse {
            get {
                return ResourceManager.GetString("Gimmick_Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopp.
        /// </summary>
        public static string Gimmick_Stop {
            get {
                return ResourceManager.GetString("Gimmick_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takt.
        /// </summary>
        public static string Gimmick_TimeSigChange {
            get {
                return ResourceManager.GetString("Gimmick_TimeSigChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von Mitte.
        /// </summary>
        public static string MaskDirection_Center {
            get {
                return ResourceManager.GetString("MaskDirection_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Uhrzeigersinn.
        /// </summary>
        public static string MaskDirection_Clockwise {
            get {
                return ResourceManager.GetString("MaskDirection_Clockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gegen Uhrzeigersinn.
        /// </summary>
        public static string MaskDirection_Counterclockwise {
            get {
                return ResourceManager.GetString("MaskDirection_Counterclockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopieren.
        /// </summary>
        public static string Menu_Copy {
            get {
                return ResourceManager.GetString("Menu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausschneiden.
        /// </summary>
        public static string Menu_Cut {
            get {
                return ResourceManager.GetString("Menu_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu.
        /// </summary>
        public static string Menu_New {
            get {
                return ResourceManager.GetString("Menu_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen.
        /// </summary>
        public static string Menu_Open {
            get {
                return ResourceManager.GetString("Menu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einfügen.
        /// </summary>
        public static string Menu_Paste {
            get {
                return ResourceManager.GetString("Menu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederholen.
        /// </summary>
        public static string Menu_Redo {
            get {
                return ResourceManager.GetString("Menu_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern Als.
        /// </summary>
        public static string Menu_SaveAs {
            get {
                return ResourceManager.GetString("Menu_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rückgängig.
        /// </summary>
        public static string Menu_Undo {
            get {
                return ResourceManager.GetString("Menu_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string MenuHeader_Edit {
            get {
                return ResourceManager.GetString("MenuHeader_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei.
        /// </summary>
        public static string MenuHeader_File {
            get {
                return ResourceManager.GetString("MenuHeader_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswählen.
        /// </summary>
        public static string MenuHeader_Select {
            get {
                return ResourceManager.GetString("MenuHeader_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kette.
        /// </summary>
        public static string Note_Chain {
            get {
                return ResourceManager.GetString("Note_Chain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Ende.
        /// </summary>
        public static string Note_EndOfChart {
            get {
                return ResourceManager.GetString("Note_EndOfChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halten.
        /// </summary>
        public static string Note_Hold {
            get {
                return ResourceManager.GetString("Note_Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maske Hinzufügen.
        /// </summary>
        public static string Note_MaskAdd {
            get {
                return ResourceManager.GetString("Note_MaskAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maske Entfernen.
        /// </summary>
        public static string Note_MaskRemove {
            get {
                return ResourceManager.GetString("Note_MaskRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↩ Wischen (mit Uhr).
        /// </summary>
        public static string Note_SlideClockwise {
            get {
                return ResourceManager.GetString("Note_SlideClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↪ Wischen (gegen Uhr).
        /// </summary>
        public static string Note_SlideCounterclockwise {
            get {
                return ResourceManager.GetString("Note_SlideCounterclockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↓ Schieben (rückwärts).
        /// </summary>
        public static string Note_SnapBackward {
            get {
                return ResourceManager.GetString("Note_SnapBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↑ Schieben (vorwärts).
        /// </summary>
        public static string Note_SnapForward {
            get {
                return ResourceManager.GetString("Note_SnapForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tippen.
        /// </summary>
        public static string Note_Touch {
            get {
                return ResourceManager.GetString("Note_Touch", resourceCulture);
            }
        }
    }
}
